/**
 * Express API Server for Autonomous AI Creator.
 * Exposes required POST /api/agent/init and GET /api/agent/feed endpoints.
 */

import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { initAgent, getAgentFeed, getAgentStatus, runAutonomousCycle } from './agent/runner.mjs';
import { PRESET_PERSONAS } from './agent/persona.mjs';
import { getStore } from './agent/memory.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 5000;

// Enable CORS and JSON parsing
app.use(cors());
app.use(express.json());

// Serve static frontend assets if built
app.use(express.static(path.join(__dirname, '../dist')));

/**
 * 1. REQUIRED ENDPOINT: POST /api/agent/init
 * Called once before evaluation to initialize agent persona.
 */
app.post('/api/agent/init', async (req, res) => {
  try {
    const payload = req.body || {};
    console.log('[API] Received POST /api/agent/init:', JSON.stringify(payload));

    const result = await initAgent(payload);

    return res.status(200).json({
      agentId: result.agentId
    });
  } catch (err) {
    console.error('[API] Error initializing agent:', err);
    return res.status(500).json({ error: 'Failed to initialize agent', message: err.message });
  }
});

/**
 * 2. REQUIRED ENDPOINT: GET /api/agent/feed?agentId=...
 * Called periodically during evaluation to retrieve posts in reverse chronological order.
 */
app.get('/api/agent/feed', (req, res) => {
  try {
    const agentId = req.query.agentId;

    if (!agentId) {
      return res.status(400).json({ error: 'Missing required query parameter: agentId' });
    }

    const feed = getAgentFeed(agentId);
    return res.status(200).json(feed);
  } catch (err) {
    console.error('[API] Error fetching feed:', err);
    return res.status(500).json({ error: 'Failed to retrieve feed', message: err.message });
  }
});

/**
 * HELPER ENDPOINTS for UI & Inspection
 */

// Get detailed status of agent
app.get('/api/agent/status', (req, res) => {
  const agentId = req.query.agentId;
  if (!agentId) {
    return res.status(400).json({ error: 'Missing agentId' });
  }
  const status = getAgentStatus(agentId);
  return res.json(status);
});

// Trigger immediate autonomous cycle (DEV/DEMO ONLY - disabled during evaluation)
// This exists purely so the team can verify the pipeline while building.
// It must NEVER be used to produce posts during actual judging, since the spec
// requires all posts to be generated by the agent on its own, without external prompts.
app.post('/api/agent/trigger', async (req, res) => {
  if (process.env.ALLOW_MANUAL_TRIGGER !== 'true') {
    return res.status(403).json({
      error: 'Manual triggering is disabled in this deployment.',
      message: 'This agent only publishes autonomously on its own schedule, per hackathon submission rules.'
    });
  }
  const { agentId } = req.body || {};
  if (!agentId) {
    return res.status(400).json({ error: 'Missing agentId' });
  }
  const result = await runAutonomousCycle(agentId);
  return res.json(result);
});

// Lets the frontend know whether the manual trigger button should render at all
app.get('/api/agent/config', (req, res) => {
  return res.json({ allowManualTrigger: process.env.ALLOW_MANUAL_TRIGGER === 'true' });
});

// Get available preset personas
app.get('/api/agent/presets', (req, res) => {
  return res.json(PRESET_PERSONAS);
});

// Fallback to index.html for SPA routing
app.get('*', (req, res) => {
  const indexPath = path.join(__dirname, '../dist/index.html');
  if (req.accepts('html') && !req.path.startsWith('/api')) {
    return res.sendFile(indexPath, (err) => {
      if (err) {
        res.type('text/plain').send('Autonomous AI Creator API Server is active. Frontend build missing or dev mode.');
      }
    });
  }
  res.status(404).json({ error: 'Not found' });
});

/**
 * On boot, re-launch the autonomous background loop for any agent that was
 * still ACTIVE when the process last stopped. Without this, a host restart
 * (e.g. Render redeploy, crash, or free-tier spin-down/wake cycle) would
 * silently freeze every previously-initialized agent's publishing loop,
 * even though its post history is still sitting safely in store.json.
 */
function rehydrateActiveAgents() {
  const store = getStore();
  const agents = store.agents || {};
  const activeIds = Object.keys(agents).filter(id => agents[id]?.status === 'ACTIVE');

  if (activeIds.length === 0) {
    console.log('[Boot] No previously-active agents to rehydrate.');
    return;
  }

  console.log(`[Boot] Rehydrating ${activeIds.length} previously-active agent(s): ${activeIds.join(', ')}`);
  for (const agentId of activeIds) {
    const persona = agents[agentId].persona;
    // Re-run initAgent with the SAME agentId so it resumes under its existing
    // identity/history instead of minting a new one.
    initAgent({ agentId, persona }).catch(err =>
      console.error(`[Boot] Failed to rehydrate agent ${agentId}:`, err)
    );
  }
}

app.listen(PORT, () => {
  console.log(`====================================================`);
  console.log(`🚀 Autonomous AI Creator API Server running on port ${PORT}`);
  console.log(`- POST /api/agent/init`);
  console.log(`- GET  /api/agent/feed?agentId=...`);
  console.log(`====================================================`);
  rehydrateActiveAgents();
});
